# Site settings
title: 飞行家
email: 962889483@qq.com
description: > # this means to ignore newlines until "baseurl:"
  淡定淡定
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wand933.github.io" # the base hostname & protocol for your site
#url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site
twitter_username: wangd933
github_username:  wand933

# Build settings
markdown: kramdown
