//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoClient.DownLoadServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://video.pandawork.net/download/", ConfigurationName="DownLoadServiceReference.DownLoadService")]
    public interface DownLoadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/download/DownLoadService/DownLoadFile", ReplyAction="http://video.pandawork.net/download/DownLoadService/DownLoadFileResponse")]
        System.IO.Stream DownLoadFile(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/download/DownLoadService/DownLoadFile", ReplyAction="http://video.pandawork.net/download/DownLoadService/DownLoadFileResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> DownLoadFileAsync(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/download/DownLoadService/GetDownLoadInfo", ReplyAction="http://video.pandawork.net/download/DownLoadService/GetDownLoadInfoResponse")]
        int GetDownLoadInfo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/download/DownLoadService/GetDownLoadInfo", ReplyAction="http://video.pandawork.net/download/DownLoadService/GetDownLoadInfoResponse")]
        System.Threading.Tasks.Task<int> GetDownLoadInfoAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DownLoadServiceChannel : VideoClient.DownLoadServiceReference.DownLoadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DownLoadServiceClient : System.ServiceModel.ClientBase<VideoClient.DownLoadServiceReference.DownLoadService>, VideoClient.DownLoadServiceReference.DownLoadService {
        
        public DownLoadServiceClient() {
        }
        
        public DownLoadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DownLoadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DownLoadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DownLoadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.Stream DownLoadFile(string fileName) {
            return base.Channel.DownLoadFile(fileName);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> DownLoadFileAsync(string fileName) {
            return base.Channel.DownLoadFileAsync(fileName);
        }
        
        public int GetDownLoadInfo(int id) {
            return base.Channel.GetDownLoadInfo(id);
        }
        
        public System.Threading.Tasks.Task<int> GetDownLoadInfoAsync(int id) {
            return base.Channel.GetDownLoadInfoAsync(id);
        }
    }
}
