//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoClient.UserServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://video.pandawork.net/user/", ConfigurationName="UserServiceReference.UserService")]
    public interface UserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/user/UserService/verifyUser", ReplyAction="http://video.pandawork.net/user/UserService/verifyUserResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VideoCommon.com.pandawork.common.entity.User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VideoCommon.com.pandawork.common.entity.Acc[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VideoCommon.com.pandawork.common.entity.Acc))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(VideoCommon.com.pandawork.common.entity.User[]))]
        object verifyUser(string userName, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/user/UserService/verifyUser", ReplyAction="http://video.pandawork.net/user/UserService/verifyUserResponse")]
        System.Threading.Tasks.Task<object> verifyUserAsync(string userName, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/user/UserService/updateUserAndAcc", ReplyAction="http://video.pandawork.net/user/UserService/updateUserAndAccResponse")]
        void updateUserAndAcc(VideoCommon.com.pandawork.common.entity.User user, VideoCommon.com.pandawork.common.entity.Acc[] accList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/user/UserService/updateUserAndAcc", ReplyAction="http://video.pandawork.net/user/UserService/updateUserAndAccResponse")]
        System.Threading.Tasks.Task updateUserAndAccAsync(VideoCommon.com.pandawork.common.entity.User user, VideoCommon.com.pandawork.common.entity.Acc[] accList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/user/UserService/updateUser", ReplyAction="http://video.pandawork.net/user/UserService/updateUserResponse")]
        void updateUser(VideoCommon.com.pandawork.common.entity.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/user/UserService/updateUser", ReplyAction="http://video.pandawork.net/user/UserService/updateUserResponse")]
        System.Threading.Tasks.Task updateUserAsync(VideoCommon.com.pandawork.common.entity.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/user/UserService/delUser", ReplyAction="http://video.pandawork.net/user/UserService/delUserResponse")]
        void delUser(VideoCommon.com.pandawork.common.entity.User user, VideoCommon.com.pandawork.common.entity.Acc[] accList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/user/UserService/delUser", ReplyAction="http://video.pandawork.net/user/UserService/delUserResponse")]
        System.Threading.Tasks.Task delUserAsync(VideoCommon.com.pandawork.common.entity.User user, VideoCommon.com.pandawork.common.entity.Acc[] accList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/user/UserService/getAllUsers", ReplyAction="http://video.pandawork.net/user/UserService/getAllUsersResponse")]
        VideoCommon.com.pandawork.common.entity.User[] getAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/user/UserService/getAllUsers", ReplyAction="http://video.pandawork.net/user/UserService/getAllUsersResponse")]
        System.Threading.Tasks.Task<VideoCommon.com.pandawork.common.entity.User[]> getAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/user/UserService/addUserAndAcc", ReplyAction="http://video.pandawork.net/user/UserService/addUserAndAccResponse")]
        bool addUserAndAcc(VideoCommon.com.pandawork.common.entity.User user, VideoCommon.com.pandawork.common.entity.Acc[] accList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/user/UserService/addUserAndAcc", ReplyAction="http://video.pandawork.net/user/UserService/addUserAndAccResponse")]
        System.Threading.Tasks.Task<bool> addUserAndAccAsync(VideoCommon.com.pandawork.common.entity.User user, VideoCommon.com.pandawork.common.entity.Acc[] accList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/user/UserService/addUser", ReplyAction="http://video.pandawork.net/user/UserService/addUserResponse")]
        VideoCommon.com.pandawork.common.entity.User addUser(VideoCommon.com.pandawork.common.entity.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/user/UserService/addUser", ReplyAction="http://video.pandawork.net/user/UserService/addUserResponse")]
        System.Threading.Tasks.Task<VideoCommon.com.pandawork.common.entity.User> addUserAsync(VideoCommon.com.pandawork.common.entity.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserServiceChannel : VideoClient.UserServiceReference.UserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<VideoClient.UserServiceReference.UserService>, VideoClient.UserServiceReference.UserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object verifyUser(string userName, string pwd) {
            return base.Channel.verifyUser(userName, pwd);
        }
        
        public System.Threading.Tasks.Task<object> verifyUserAsync(string userName, string pwd) {
            return base.Channel.verifyUserAsync(userName, pwd);
        }
        
        public void updateUserAndAcc(VideoCommon.com.pandawork.common.entity.User user, VideoCommon.com.pandawork.common.entity.Acc[] accList) {
            base.Channel.updateUserAndAcc(user, accList);
        }
        
        public System.Threading.Tasks.Task updateUserAndAccAsync(VideoCommon.com.pandawork.common.entity.User user, VideoCommon.com.pandawork.common.entity.Acc[] accList) {
            return base.Channel.updateUserAndAccAsync(user, accList);
        }
        
        public void updateUser(VideoCommon.com.pandawork.common.entity.User user) {
            base.Channel.updateUser(user);
        }
        
        public System.Threading.Tasks.Task updateUserAsync(VideoCommon.com.pandawork.common.entity.User user) {
            return base.Channel.updateUserAsync(user);
        }
        
        public void delUser(VideoCommon.com.pandawork.common.entity.User user, VideoCommon.com.pandawork.common.entity.Acc[] accList) {
            base.Channel.delUser(user, accList);
        }
        
        public System.Threading.Tasks.Task delUserAsync(VideoCommon.com.pandawork.common.entity.User user, VideoCommon.com.pandawork.common.entity.Acc[] accList) {
            return base.Channel.delUserAsync(user, accList);
        }
        
        public VideoCommon.com.pandawork.common.entity.User[] getAllUsers() {
            return base.Channel.getAllUsers();
        }
        
        public System.Threading.Tasks.Task<VideoCommon.com.pandawork.common.entity.User[]> getAllUsersAsync() {
            return base.Channel.getAllUsersAsync();
        }
        
        public bool addUserAndAcc(VideoCommon.com.pandawork.common.entity.User user, VideoCommon.com.pandawork.common.entity.Acc[] accList) {
            return base.Channel.addUserAndAcc(user, accList);
        }
        
        public System.Threading.Tasks.Task<bool> addUserAndAccAsync(VideoCommon.com.pandawork.common.entity.User user, VideoCommon.com.pandawork.common.entity.Acc[] accList) {
            return base.Channel.addUserAndAccAsync(user, accList);
        }
        
        public VideoCommon.com.pandawork.common.entity.User addUser(VideoCommon.com.pandawork.common.entity.User user) {
            return base.Channel.addUser(user);
        }
        
        public System.Threading.Tasks.Task<VideoCommon.com.pandawork.common.entity.User> addUserAsync(VideoCommon.com.pandawork.common.entity.User user) {
            return base.Channel.addUserAsync(user);
        }
    }
}
