//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoClient.RegionServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://video.pandawork.net/region/", ConfigurationName="RegionServiceReference.RegionService")]
    public interface RegionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/region/RegionService/addRegion", ReplyAction="http://video.pandawork.net/region/RegionService/addRegionResponse")]
        bool addRegion(VideoCommon.com.pandawork.common.entity.Region region);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/region/RegionService/addRegion", ReplyAction="http://video.pandawork.net/region/RegionService/addRegionResponse")]
        System.Threading.Tasks.Task<bool> addRegionAsync(VideoCommon.com.pandawork.common.entity.Region region);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/region/RegionService/getRegionById", ReplyAction="http://video.pandawork.net/region/RegionService/getRegionByIdResponse")]
        VideoCommon.com.pandawork.common.dto.RegionDTO getRegionById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/region/RegionService/getRegionById", ReplyAction="http://video.pandawork.net/region/RegionService/getRegionByIdResponse")]
        System.Threading.Tasks.Task<VideoCommon.com.pandawork.common.dto.RegionDTO> getRegionByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/region/RegionService/updateRegion", ReplyAction="http://video.pandawork.net/region/RegionService/updateRegionResponse")]
        void updateRegion(VideoCommon.com.pandawork.common.entity.Region region);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/region/RegionService/updateRegion", ReplyAction="http://video.pandawork.net/region/RegionService/updateRegionResponse")]
        System.Threading.Tasks.Task updateRegionAsync(VideoCommon.com.pandawork.common.entity.Region region);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/region/RegionService/delRegion", ReplyAction="http://video.pandawork.net/region/RegionService/delRegionResponse")]
        void delRegion(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/region/RegionService/delRegion", ReplyAction="http://video.pandawork.net/region/RegionService/delRegionResponse")]
        System.Threading.Tasks.Task delRegionAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/region/RegionService/getAllRegions", ReplyAction="http://video.pandawork.net/region/RegionService/getAllRegionsResponse")]
        VideoCommon.com.pandawork.common.dto.RegionDTO[] getAllRegions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/region/RegionService/getAllRegions", ReplyAction="http://video.pandawork.net/region/RegionService/getAllRegionsResponse")]
        System.Threading.Tasks.Task<VideoCommon.com.pandawork.common.dto.RegionDTO[]> getAllRegionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/region/RegionService/findChildren", ReplyAction="http://video.pandawork.net/region/RegionService/findChildrenResponse")]
        VideoCommon.com.pandawork.common.dto.RegionDTO[] findChildren(int id, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/region/RegionService/findChildren", ReplyAction="http://video.pandawork.net/region/RegionService/findChildrenResponse")]
        System.Threading.Tasks.Task<VideoCommon.com.pandawork.common.dto.RegionDTO[]> findChildrenAsync(int id, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/region/RegionService/createTreeById", ReplyAction="http://video.pandawork.net/region/RegionService/createTreeByIdResponse")]
        VideoCommon.com.pandawork.common.dto.RegionDTO createTreeById(int id, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://video.pandawork.net/region/RegionService/createTreeById", ReplyAction="http://video.pandawork.net/region/RegionService/createTreeByIdResponse")]
        System.Threading.Tasks.Task<VideoCommon.com.pandawork.common.dto.RegionDTO> createTreeByIdAsync(int id, int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegionServiceChannel : VideoClient.RegionServiceReference.RegionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegionServiceClient : System.ServiceModel.ClientBase<VideoClient.RegionServiceReference.RegionService>, VideoClient.RegionServiceReference.RegionService {
        
        public RegionServiceClient() {
        }
        
        public RegionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool addRegion(VideoCommon.com.pandawork.common.entity.Region region) {
            return base.Channel.addRegion(region);
        }
        
        public System.Threading.Tasks.Task<bool> addRegionAsync(VideoCommon.com.pandawork.common.entity.Region region) {
            return base.Channel.addRegionAsync(region);
        }
        
        public VideoCommon.com.pandawork.common.dto.RegionDTO getRegionById(int id) {
            return base.Channel.getRegionById(id);
        }
        
        public System.Threading.Tasks.Task<VideoCommon.com.pandawork.common.dto.RegionDTO> getRegionByIdAsync(int id) {
            return base.Channel.getRegionByIdAsync(id);
        }
        
        public void updateRegion(VideoCommon.com.pandawork.common.entity.Region region) {
            base.Channel.updateRegion(region);
        }
        
        public System.Threading.Tasks.Task updateRegionAsync(VideoCommon.com.pandawork.common.entity.Region region) {
            return base.Channel.updateRegionAsync(region);
        }
        
        public void delRegion(int id) {
            base.Channel.delRegion(id);
        }
        
        public System.Threading.Tasks.Task delRegionAsync(int id) {
            return base.Channel.delRegionAsync(id);
        }
        
        public VideoCommon.com.pandawork.common.dto.RegionDTO[] getAllRegions() {
            return base.Channel.getAllRegions();
        }
        
        public System.Threading.Tasks.Task<VideoCommon.com.pandawork.common.dto.RegionDTO[]> getAllRegionsAsync() {
            return base.Channel.getAllRegionsAsync();
        }
        
        public VideoCommon.com.pandawork.common.dto.RegionDTO[] findChildren(int id, int userId) {
            return base.Channel.findChildren(id, userId);
        }
        
        public System.Threading.Tasks.Task<VideoCommon.com.pandawork.common.dto.RegionDTO[]> findChildrenAsync(int id, int userId) {
            return base.Channel.findChildrenAsync(id, userId);
        }
        
        public VideoCommon.com.pandawork.common.dto.RegionDTO createTreeById(int id, int userId) {
            return base.Channel.createTreeById(id, userId);
        }
        
        public System.Threading.Tasks.Task<VideoCommon.com.pandawork.common.dto.RegionDTO> createTreeByIdAsync(int id, int userId) {
            return base.Channel.createTreeByIdAsync(id, userId);
        }
    }
}
